#!/usr/bin/env python
"""
Strip outputs from an IPython Notebook
"""
 
import io
import sys
 
from IPython.nbformat import current
 
def strip_output(nb):
    """strip the outputs from a notebook object"""
    nb.metadata.pop('signature', None)
    for cell in nb.worksheets[0].cells:
        if 'outputs' in cell:
            cell['outputs'] = []
        if 'prompt_number' in cell:
            cell.pop('prompt_number')
    return nb
 
if __name__ == '__main__':
    for filename in sys.argv[1:]:
        with io.open(filename, 'r', encoding='utf8') as f:
            nb = current.read(f, 'json')
        nb = strip_output(nb)
        with io.open(filename, 'w', encoding='utf8') as f:
            current.write(nb, f, 'json')